import React from "react";

export const products = [
  {
    id: 1,
    name: "product1",
    img: "./images/image1.png",
    price: "$15",
    desc: "lksjlkdfjlkdsjlkfjdslkfjsljflsdjflj",
    quantity: 1,
  },
  {
    id: 2,
    name: "product2",
    img: "./images/image3.png",
    price: "$15",
    desc: "lksjlkdfjlkdsjlkfjdslkfjsljflsdjflj",
    quantity: 1,
  },
  {
    id: 3,
    name: "product3",
    img: "./images/image2.png",
    price: "$15",
    desc: "lksjlkdfjlkdsjlkfjdslkfjsljflsdjflj",
    quantity: 1,
  },
  {
    id: 4,
    name: "product4",
    img: "./images/image4.png",
    price: "$15",
    desc: "lksjlkdfjlkdsjlkfjdslkfjsljflsdjflj",
    quantity: 1,
  },
  {
    id: 5,
    name: "product5",
    img: "./images/image3.png",
    price: "$15",
    desc: "lksjlkdfjlkdsjlkfjdslkfjsljflsdjflj",
    quantity: 0,
  },
  {
    id: 6,
    name: "product6",
    img: "./images/image4.png",
    price: "$15",
    desc: "lksjlkdfjlkdsjlkfjdslkfjsljflsdjflj",
    quantity: 0,
  },
  {
    id: 7,
    name: "product7",
    img: "./images/image2.png",
    price: "$15",
    desc: "lksjlkdfjlkdsjlkfjdslkfjsljflsdjflj",
    quantity: 0,
  },
  {
    id: 8,
    name: "product8",
    img: "./images/image3.png",
    price: "$15",
    desc: "lksjlkdfjlkdsjlkfjdslkfjsljflsdjflj",
    quantity: 0,
  },
  {
    id: 9,
    name: "product9",
    img: "./images/image1.png",
    price: "$15",
    desc: "lksjlkdfjlkdsjlkfjdslkfjsljflsdjflj",
    quantity: 0,
  },
  {
    id: 10,
    name: "product10",
    img: "./images/image2.png",
    price: "$15",
    desc: "lksjlkdfjlkdsjlkfjdslkfjsljflsdjflj",
    quantity: 0,
  },
  {
    id: 11,
    name: "product11",
    img: "./images/image1.png",
    price: "$15",
    desc: "lksjlkdfjlkdsjlkfjdslkfjsljflsdjflj",
    quantity: 0,
  },
  {
    id: 12,
    name: "product12",
    img: "./images/image4.png",
    price: "$15",
    desc: "lksjlkdfjlkdsjlkfjdslkfjsljflsdjflj",
    quantity: 0,
  },
  {
    id: 13,
    name: "product13",
    img: "./images/image3.png",
    price: "$15",
    desc: "lksjlkdfjlkdsjlkfjdslkfjsljflsdjflj",
    quantity: 0,
  },
  {
    id: 14,
    name: "product14",
    img: "./images/image3.png",
    price: "$15",
    desc: "lksjlkdfjlkdsjlkfjdslkfjsljflsdjflj",
    quantity: 0,
  },
  {
    id: 15,
    name: "product15",
    img: "./images/image3.png",
    price: "$15",
    desc: "lksjlkdfjlkdsjlkfjdslkfjsljflsdjflj",
    quantity: 0,
  },
  {
    id: 16,
    name: "product16",
    img: "./images/image3.png",
    price: "$15",
    desc: "lksjlkdfjlkdsjlkfjdslkfjsljflsdjflj",
    quantity: 0,
  },
];
